// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_srqr_CKgBu1n9rwoHoU5r0VES_9diPg',
    appId: '1:356971754168:web:a759d338cc0e0291103a4d',
    messagingSenderId: '356971754168',
    projectId: 'growplants-48745',
    authDomain: 'growplants-48745.firebaseapp.com',
    storageBucket: 'growplants-48745.firebasestorage.app',
    measurementId: 'G-3WKGRGV076',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSpnH86Qs6xyYWYq28tSbzBcPO8hgMR4',
    appId: '1:356971754168:android:754feb6430f0e15b103a4d',
    messagingSenderId: '356971754168',
    projectId: 'growplants-48745',
    storageBucket: 'growplants-48745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSwaVKqnA0_fm70snvyAJTnO60XjkJYQ',
    appId: '1:356971754168:ios:fba4b42222cabd90103a4d',
    messagingSenderId: '356971754168',
    projectId: 'growplants-48745',
    storageBucket: 'growplants-48745.firebasestorage.app',
    iosBundleId: 'com.example.growplants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_srqr_CKgBu1n9rwoHoU5r0VES_9diPg',
    appId: '1:356971754168:web:fb5dcdff6ee0431a103a4d',
    messagingSenderId: '356971754168',
    projectId: 'growplants-48745',
    authDomain: 'growplants-48745.firebaseapp.com',
    storageBucket: 'growplants-48745.firebasestorage.app',
    measurementId: 'G-NC5PL49BFY',
  );
}
